# - configuration & global variables, e.g. '{{ site.title }}'
# - server needs to be restarted if file is modified

title:              Dataslice
email:              skms4885@gmail.com
description:        Data tutorials, tips, and tricks
author:             Minsub Kim
baseurl:            ""
url:                "https://harry4885.github.io"

# url       : http://jekyll.github.io/
# baseurl   : example/
# page path : 2014/welcome-to-jekyll.html
# full path : http://jhekyll.github.io/example/2014/welcome-to-jekyll.html

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
